### ISSUE TITLE
Add examples on how we can create the fabric-sdk-go config.yaml file.

### ISSUE THREAD

**Issue by GeoMisiak** [hyperledger/fabric-sdk-go#209]
According to the fabric-samples, within the first-network and test-network there are two templates, one json file and one yaml file that are being created when network started. Using the ccp-generate.sh we can fill with these templates with the latest pem files. These files will be used later from the API in order to be able to execute SubmitTransaction and EvaluateTransaction and interact with the smart contract. 

What I am trying to achieve?I am trying to fetch the latest block for from the channel for example, using qscc queries against peers. When I am trying to load this file again in order to be able to create a channel context using the:
`sdk, err := fabsdk.New(config.FromFile("<path to connection-org1.json file>"))`

**Comment by afrancoc2000** [comment]
Hi @GeoMisiak here is the template for the config.yaml https://github.com/hyperledger/fabric-sdk-go/blob/main/pkg/core/config/testdata/template/config.yaml and in this folder you can find some examples: https://github.com/hyperledger/fabric-sdk-go/tree/main/test/fixtures/config What the error is telling you is that you need a crypto path or a list of users under organization something like this:

With cryptoPath:
```
organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: /go/src/github.com/devcontainer/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
```

With users:
```
organizations:
  Org1:
    mspid: Org1MSP
    users:
      Admin:
        cert:
          path: /go/src/github.com/devcontainer/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
        key:
          path: /go/src/github.com/devcontainer/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem
```

Hope it helps
